FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow pymysql boto3

EXPOSE 5000

CMD mlflow server \
  --host 0.0.0.0 \
  --port 5000 \
  --backend-store-uri mysql+pymysql://mlflow:mlflow_pwd@mysql-db:3306/mlflow \
  --default-artifact-root s3://mlflow
